# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8bac4f0bbb0bc29459c0d4ba82aa023db888b872728e299d46be1497e6114b1dc86b66dba5cb0196a494c9f76fff1a16f0d5a725ffcc6e08d2da95a800b9b43

test:
  secret_key_base: 9ccd7d939233658e1b95e077f5761ab0bac104d3a58cf2ee2bd16fc1c3b1f8891b9e71a24fffc302565bee1462ea7bd679e8c4e5eb9ba188f69f6bc4e066062a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
